crustcrawler:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
    gains:
      joint_1: {p: 0, i: 0, d: 0}
      joint_2: {p: 0, i: 0, d: 0}
      joint_3: {p: 0, i: 0, d: 0}
